export const Strings = {
    amount: "Amount",
    date: 'Date',
    expense: "Expense",
    income: "Income",
    addCategory: "Add category",
    category: "Category",
    downloadPdf: "Download pdf",
    delete: "Delete",
    viewCategory: "View category",
    seeAll: "See all",
    edit: 'Edit',
    addIncome: "Add income",
    editIncome: "Edit income",
    addExpense: "Add expense",
    dailyExpense: 'Daily expense',
    editExpense: "Edit expense",
    name: "Name",
    options: "Options",
    search: "Search",
    noMoreItem: "No more item",
    editCategory: "Edit category",
    updateCategory: "Update category",
    notes: "Notes",
    updateIncome: "Update Income",
    description: "Description",
    categoryName: "Category name",
    categoryType: "Category type",
    monthlyExpense: "Monthly expense",
    categoryIcon: "Category icon",
    monthlyIncome: "Mothly Income",
    month: "Month",
    monthlyExpenseVsIncome: "Montly expense vs income",
    time: 'Time',
    viewIncome: 'View income',
    view: "View",
    updateExpense: "Update expense",
    viewExpense: "View expense"
}